# Generated by Django 4.2 on 2023-04-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imgserch', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='req',
            new_name='request',
        ),
    ]
